name: tf_geo
dependencies:
  - absl-py=1.4.0
  - affine=2.4.0
  - anyio=3.5.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.0
  - boost-cpp=1.74.0
  - bottleneck=1.3.5
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.4.26
  - cairo=1.16.0
  - certifi=2022.6.15
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.0.0
  - comm=0.1.2
  - contextily=1.3.0
  - contourpy=1.0.5
  - cryptography=38.0.1
  - curl=7.82.0
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2022.5.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dm-tree=0.1.7
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.5.0
  - fftw=3.3.9
  - fiona=1.8.22
  - flit-core=3.6.0
  - folium=0.14.0
  - fontconfig=2.14.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - freexl=1.0.6
  - fsspec=2022.3.0
  - gast=0.5.3
  - gdal=3.0.2
  - geographiclib=1.52
  - geopandas=0.12.2
  - geopandas-base=0.12.2
  - geopy=2.3.0
  - geos=3.9.1
  - geotiff=1.7.0
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.6.0
  - hdf4=4.2.13
  - hdf5=1.12.1
  - icu=68.1
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - importlib-metadata=4.11.3
  - ipykernel=6.19.2
  - ipython=8.7.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - json-c=0.13.1
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter=1.0.0
  - jupyter_client=7.4.8
  - jupyter_console=6.4.4
  - jupyter_core=5.1.1
  - jupyter_server=1.23.4
  - jupyterlab=3.5.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.16.5
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - kealib=1.4.14
  - kiwisolver=1.4.4
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libcurl=7.82.0
  - libcxx=14.0.6
  - libdap4=3.19.1
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgdal=3.0.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libkml=1.3.0
  - libllvm12=12.0.0
  - libnetcdf=4.8.1
  - libnghttp2=1.46.0
  - libopenblas=0.3.21
  - libpng=1.6.37
  - libpq=12.9
  - libpysal=4.7.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzip=1.8.0
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - locket=1.0.0
  - lxml=4.9.1
  - lz4-c=1.9.4
  - mapclassify=2.5.0
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mercantile=1.2.1
  - mistune=0.8.4
  - movingpandas=0.16.0
  - munch=2.5.0
  - munkres=1.1.4
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - networkx=2.7.1
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openjpeg=2.3.0
  - openssl=1.1.1u
  - packaging=22.0
  - pandas=1.5.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - path=16.2.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - pixman=0.40.0
  - platformdirs=2.5.2
  - ply=3.11
  - pointpats=2.3.0
  - poppler=0.81.0
  - poppler-data=0.4.12
  - proj=7.2.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyproj=3.1.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.15
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pytz=2022.7
  - pywavelets=1.3.0
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.3.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - rasterio=1.2.10
  - readline=8.2
  - requests=2.28.1
  - rtree=1.0.1
  - scikit-image=0.19.2
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - seaborn=0.11.2
  - send2trash=1.8.0
  - setuptools=65.5.0
  - shapely=2.0.1
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - snuggs=1.4.7
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - stack_data=0.2.0
  - tensorflow-probability=0.14.0
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tifffile=2021.7.2
  - tiledb=2.3.3
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.11.2
  - tornado=6.2
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.13
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xerces-c=3.2.3
  - xyzservices=2023.5.0
  - xz=5.2.8
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - keras==2.10.0
    - tensorflow-macos==2.10.0
    - tensorflow-metal==0.6.0
    - tensorflow-probability==0.14.0
